version: '3.3'
services:
  dadbard-dev:
    build: 
        context: .
        dockerfile: ./docker.dockerfile
    entrypoint: /bin/bash
    environment: 
      - R_CI=20Vyy1jaiUtFow
      - R_CS=qVqTXGlZn11twTUEUrC7D8OlaBw
      - R_UA=DadBard
    ports:
    - "8000:8000"
    volumes:
    - .:/app
  dadbard-run:
    build:
      dockerfile: ./docker.dockerfile
      context: .
    environment: 
      - R_CI=20Vyy1jaiUtFow
      - R_CS=qVqTXGlZn11twTUEUrC7D8OlaBw
      - R_UA=DadBard      
    ports:
    - "8000:8000"
    volumes:
    - .:/app    
